# Generated by Django 4.2.4 on 2023-11-14 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0006_curso_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='avatar',
            name='descripcion',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='avatar',
            name='link',
            field=models.URLField(null=True),
        ),
    ]
